import Head from 'next/head'
// import Image from 'next/image'
import {useRouter} from 'next/router'


export default function Home() {
  const router = useRouter();

  const handleClick = () => {
    router.push('/school')
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Students</h1>

        <button onClick={handleClick} className="text-xl py-2 px-4 bg-red-500 rounded text-white m-8">Go to School</button>
      </main>
    </>
  )
}
